---
cilium_chart:
  gateway_api_crds_url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.0/experimental-install.yaml
  name: cilium
  repository:
    name: cilium
    url: https://helm.cilium.io
  timeout: 10m0s
  version: v1.19.1

cilium_intent_defaults:
  namespace: kube-system
  endpoint_slice:
    enabled: true
  kube_proxy_replacement: true
  priority_class_name: system-node-critical
  routing:
    mode: native
    auto_direct_node_routes: true
    direct_routing_skip_unreachable: true
  bpf:
    masquerade: true
  envoy:
    enabled: false
  gateway_api:
    enabled: false
  hubble:
    enabled: false
  ingress_controller:
    enabled: false
  ipam:
    operator:
      cluster_pool: 10.42.0.0/16
  replica_count:
    single_node: 1
  pod_disruption_budget:
    enabled: true
    max_unavailable: 1
  rollout:
    cilium_pods: true
    operator_pods: true
  agent:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 256Mi
  cgroup:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
  cni:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
  operator:
    desired_replicas: 2
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi
