---
rancher_vars:
  kubernetes:
    agent_tls_mode: strict
    anti_affinity: preferred
    audit_log:
      enabled: false
      level: 0
    bootstrap_password: admin
    helm:
      chart:
        name: rancher
        version: 2.13.3
      repository:
        name: stable
        org: rancher-stable
        url: https://releases.rancher.com/server-charts/stable
    hostname: null
    ingress:
      class_name: cilium
      extra_annotations: {}
      tls:
        secret_name: tls-rancher-ingress
        source: rancher
    letsencrypt:
      email: null
      environment: production
      ingress:
        class: cilium
    namespace: cattle-system
    network_exposure:
      type: ingress
    private_ca: false
    replicas: 3
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
