---
k3s_node:
  # Whether this node should initialize the embedded etcd control plane.
  cluster_init: false

node_identity:
  # Hostname to enforce on this Raspberry Pi node during OS prep.
  hostname: k8s-rpi3
