---
- name: Role Facts
  ansible.builtin.import_tasks:
    file: facts.yaml

- name: Role Provisioning
  notify: Start kubernetes service
  block:
    - name: Create configuration directory
      ansible.builtin.file:
        path: '{{ k3s_map.node.directory.config }}'
        state: directory
        owner: root
        group: root
        mode: '755'

    - name: Set role postinstall fact
      ansible.builtin.set_fact:
        k3s_postinstall: false

    - name: Create configuration file
      ansible.builtin.template:
        src: config.j2
        dest: '{{ k3s_project.cluster.config }}'
        owner: root
        group: root
        mode: '600'

    - name: Create kubelet configuration file
      ansible.builtin.template:
        src: config_kubelet.j2
        dest: '{{ k3s_project.cluster.config_kubelet }}'
        owner: root
        group: root
        mode: '644'

    - name: Get installed k3s version
      ansible.builtin.command:
        cmd: '{{ k3s_node.binary }} --version'
      changed_when: false
      failed_when: false
      register: k3s_installed_version

    - name: Get k3s service file statistics
      ansible.builtin.stat:
        path: /etc/systemd/system/{{ k3s_node.service.name }}.service
      changed_when: false
      register: k3s_service_file

    - name: Install k3s binary
      ansible.builtin.shell: |
        set -o errexit -o nounset -o pipefail
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash
      environment:
        INSTALL_K3S_EXEC: "{{ k3s_node.service.type }}{{ ' --debug' if k3s_vars.service.debug else '' }}"
        INSTALL_K3S_SKIP_START: 'true'
        INSTALL_K3S_VERSION: '{{ k3s_vars.release.k3s.version }}'
      when:
        - k3s_installed_version.rc != 0 or k3s_vars.release.k3s.version not in k3s_installed_version.stdout
          or not k3s_service_file.stat.exists

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Role Configuration
  ansible.builtin.import_tasks:
    file: configuration.yaml

- name: Server Configuration
  notify: Restart kubernetes service
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Set role postinstall fact
      ansible.builtin.set_fact:
        k3s_postinstall: true

    - name: Update server configuration file
      ansible.builtin.template:
        src: config.j2
        dest: '{{ k3s_project.cluster.config }}'
        owner: root
        group: root
        mode: '600'
