router bgp 65000
bgp router-id 192.168.3.1
!
neighbor 192.168.3.243 remote-as 65001
neighbor 192.168.3.243 description k8s-rpi1
!
neighbor 192.168.3.191 remote-as 65001
neighbor 192.168.3.191 description k8s-rpi2
!
neighbor 192.168.3.108 remote-as 65001
neighbor 192.168.3.108 description k8s-rpi3
!
address-family ipv4
neighbor 192.168.3.243 activate
neighbor 192.168.3.243 soft-reconfiguration inbound
neighbor 192.168.3.243 route-map CILIUM-LB-IN in
neighbor 192.168.3.243 route-map CILIUM-LB-OUT out
neighbor 192.168.3.191 activate
neighbor 192.168.3.191 soft-reconfiguration inbound
neighbor 192.168.3.191 route-map CILIUM-LB-IN in
neighbor 192.168.3.191 route-map CILIUM-LB-OUT out
neighbor 192.168.3.108 activate
neighbor 192.168.3.108 soft-reconfiguration inbound
neighbor 192.168.3.108 route-map CILIUM-LB-IN in
neighbor 192.168.3.108 route-map CILIUM-LB-OUT out
exit-address-family
!
exit
!
route-map CILIUM-LB-IN permit 10
match ip address prefix-list CILIUM-LB-VIPS
exit
!
route-map CILIUM-LB-OUT deny 10
exit
!
ip prefix-list CILIUM-LB-VIPS seq 5 permit 192.168.3.3/32
