---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role }}'
    tasks_from: facts
  loop:
    - k3s
    - cert-manager
    - cilium
    - rancher
  loop_control:
    loop_var: role

- name: Role Validation
  when: (ansible_run_tags in [(), ('all',)]) or ('rancher' in ansible_run_tags)
  run_once: true
  block:
    - name: Validate hostname value
      ansible.builtin.assert:
        that:
          - rancher_map.ingress.hostname | length > 0
        fail_msg: Rancher hostname must resolve to a non-empty value.

    - name: Validate ingress tls source
      ansible.builtin.assert:
        that:
          - rancher_vars.kubernetes.ingress.tls.source in ['rancher', 'letsEncrypt', 'secret']
        fail_msg: Rancher ingress tls source must be one of rancher, letsEncrypt or secret.

    - name: Validate letsencrypt email value
      ansible.builtin.assert:
        that:
          - rancher_vars.kubernetes.letsencrypt.email is not none
          - rancher_vars.kubernetes.letsencrypt.email | length > 0
        fail_msg: Rancher Let's Encrypt installs require a non-empty email address.
      when: rancher_vars.kubernetes.ingress.tls.source == 'letsEncrypt'

    - name: Validate release index url
      ansible.builtin.uri:
        url: '{{ rancher_project.release.index }}'
        timeout: 5
      register: rancher_result
      delay: 1
      retries: 3
      until: rancher_result is not failed

    - name: Validate release file url
      ansible.builtin.uri:
        url: '{{ rancher_project.release.url }}/{{ rancher_project.release.file }}'
        timeout: 5
      register: rancher_result
      delay: 1
      retries: 3
      until: rancher_result is not failed

    - name: Chart Validation
      block:
        - name: Update repository
          kubernetes.core.helm_repository:
            name: '{{ rancher_vars.kubernetes.helm.repository.org }}'
            repo_url: '{{ rancher_map.helm.repository.url }}'
            force_update: true
          when: not rancher_map.helm.is_oci

        - name: Validate cluster kubeconfig path
          ansible.builtin.stat:
            path: '{{ k3s_project.cluster.kubeconfig }}'
          register: rancher_kubeconfig
          changed_when: false

        - name: Get deployed chart release info
          kubernetes.core.helm_info:
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ rancher_vars.kubernetes.helm.chart.name }}'
            namespace: '{{ rancher_vars.kubernetes.namespace }}'
          register: rancher_release
          when: rancher_kubeconfig.stat.exists
          changed_when: false

        - name: Set comparison fact
          ansible.builtin.set_fact:
            rancher_comparison:
              chart: '{{ rancher_vars.kubernetes.helm.chart.version }}'
              release: "{{ rancher_release.status.chart | default('0') | regex_search('[0-9][0-9A-Za-z.-]*') }}"

        - name: Validate chart values
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.template', 'values.j2') }}"

        - name: Set chart values fact
          ansible.builtin.set_fact:
            rancher_chart_values: "{{ lookup('ansible.builtin.template', 'values.j2') | trim | from_yaml }}"

        - name: Chart Deployment Simulation
          when:
            - rancher_comparison.release is version('0', '>')
            - rancher_comparison.release != rancher_comparison.chart
          block:
            - name: Simulate chart deployment
              ansible.builtin.command:
                cmd: >-
                  helm diff upgrade
                    {{ rancher_vars.kubernetes.helm.chart.name }}
                    {{ rancher_map.helm.chart.reference }}
                    --kubeconfig {{ k3s_project.cluster.kubeconfig }}
                    --namespace {{ rancher_vars.kubernetes.namespace }}
                    --version {{ rancher_vars.kubernetes.helm.chart.version }}
                    --context 3 --values -
                stdin: '{{ rancher_chart_values | to_yaml }}'
              register: rancher_result
              delay: 1
              retries: 3
              until: rancher_result is not failed
              changed_when: false

            - name: Chart deployment simulation result
              ansible.builtin.debug:
                msg: "{{ rancher_result.stdout if rancher_result.stdout | length > 0 else 'No chart deployment errors found.' }}"

            - name: Compare chart values
              ansible.builtin.command:
                cmd: >-
                  bash -c "{{
                    ' '.join(
                      [
                        'diff',
                        '-u',
                        '<(curl',
                        '-fsSL ' + rancher_project.release.url + '/rancher-' + rancher_comparison.release + '.tgz | tar -xzOf - rancher/values.yaml)',
                        '<(curl',
                        '-fsSL ' + rancher_project.release.url + '/rancher-' + rancher_comparison.chart + '.tgz | tar -xzOf - rancher/values.yaml)',
                      ]
                    )
                  }}"
              register: rancher_result
              delay: 1
              retries: 3
              until: rancher_result is not failed
              changed_when: false
              failed_when: rancher_result.rc > 1

            - name: Chart values comparison result
              ansible.builtin.debug:
                msg: "{{ rancher_result.stdout if rancher_result.stdout | length > 0 else 'No chart comparison changes found.' }}"
