---
- name: Role Facts
  ansible.builtin.include_role:
    name: '{{ role_name }}'
    tasks_from: facts
  loop:
    - k3s
    - cert-manager
  loop_control:
    loop_var: role_name

- name: Role Validation
  ansible.builtin.import_tasks:
    file: validation.yaml
  any_errors_fatal: true

- name: Role Provisioning
  when: inventory_hostname in k3s_map.server.hosts
  block:
    - name: Add repository
      kubernetes.core.helm_repository:
        kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
        name: '{{ cert_manager_chart.repository.name }}'
        repo_url: '{{ cert_manager_chart.repository.url }}'
        force_update: true
      register: cert_manager_result
      delay: 1
      retries: 3
      until: cert_manager_result is not failed
      when: not cert_manager_chart.is_oci

    - name: Chart Setup
      run_once: true
      block:
        - name: Install chart
          kubernetes.core.helm:
            chart_ref: '{{ cert_manager_chart.chart_ref }}'
            chart_version: '{{ cert_manager_chart.version }}'
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            name: '{{ cert_manager_chart.name }}'
            namespace: '{{ cert_manager_chart.namespace }}'
            timeout: '{{ cert_manager_chart.timeout }}'
            values: "{{ lookup('ansible.builtin.template', 'values.j2') | from_yaml }}"
            create_namespace: true
            update_repo_cache: '{{ not cert_manager_chart.is_oci }}'
            wait: true
          register: cert_manager_result
          delay: 1
          retries: 3
          until: cert_manager_result is not failed

        - name: Create self-signed cluster issuer
          kubernetes.core.k8s:
            definition: "{{ lookup('ansible.builtin.template', 'cluster_issuer.j2') | from_yaml }}"
            kubeconfig: '{{ k3s_project.cluster.kubeconfig }}'
            wait: true
