---
k3s_vars:
  cluster:
    controlplane:
      tainted: false
    domain: cluster.local
    disable:
      - servicelb
      - traefik
    egress_selector_mode: agent
    kubeconfig:
      local: true
      # -- Local `/.kube` directory path
      path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube"
      mode: "0644"
    networking:
      disable_kube_proxy: true
      disable_network_policy: true
      flannel_backend: none
    service:
      host: 127.0.0.1
      port: 6444
    tls_san:
      - "{{ groups.server[0] }}"
  release:
    k3s:
      name: k3s
      version: v1.35.3+k3s1
  server:
    api:
      host: "{{ groups.server[0] }}"
      port: 6443
  service:
    debug: false
