k3s:
    token: ENC[AES256_GCM,data:iMm2sz5eGKDFLrsbJ6wCckXQ9CkDOg5kYHR7ceOl6M5wn2KKHgf1xhI4PtsKUwYF+iv1k5ma2PU5LkF0mLS+EQ==,iv:jHK4siovtQh1ZTrdxyoZx8YMVes403Dz3R7cUE6qc0w=,tag:T+5H8zAYa+HmLdVR22fVFQ==,type:str]
cert_manager:
    cloudflare:
        api_token: ENC[AES256_GCM,data:yMe7Rh8nma0GfXhSy5NcMTa/7+DXXETqUQ9najsjB5y3LJKcYKwOmCigPIHtoMIBKcvkiu0=,iv:poucGoEkndLjl5Fx9p+fYog2aIs59HmWWnyIIW06V4s=,tag:GcXzqtKYUIjy0D8qurzijg==,type:str]
rancher:
    bootstrap_password: ENC[AES256_GCM,data:pj+fCYtrVC9w0ZoVCD30eQE6pe5j,iv:ThbfjHq8C1BSiTbaXm/caXGtWR0d4AqEG2/sWcteCGc=,tag:qEYz9PwX2uDVFxIIqoC06A==,type:str]
sops:
    age:
        - recipient: age1sl7k6nw404ykru7qyfnpvpamghrvjtd56j5kphk54tnhwawszf5sx4qfna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdDdYa2VFVmlmc3E2eExi
            TmlIQi9oRlJheUw3VVkxVWlEcEI2bEVhNlh3CnVmNzVQUGVUWkJVcG83UHdvcXBK
            a09lZ2ptLzNWUHBFNFNZOGFBSENvYVkKLS0tIHB1MWtNWldqdDBOS1BvZGV1ZENa
            QXJJUTIySk9MTnFVQ3Q0cmIrMnlMS3MKkn5XINuo0Ay45ZgpmHL493rXl81K2BVw
            Ztt0rGnMoIGlJRe73HJ3+l3YAveF+wT+bD5SlNTL3L4M0I83TLmlCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T16:00:42Z"
    mac: ENC[AES256_GCM,data:z5b6v09YO0MYebab5JpxBVfbm7l2fvUcBaR308tOVz+TKAL3lUypWUjedTdVMiTcMtRhTf7Cn93pcsNfQySVztFtYiCwQHk6kjv16e1HhjbwB2NYSjcY9aiGtgXGEPZzU/ktcgmnyhxx4lNSnE2BFRt2HDfOk3lM9XE2h5+KkwA=,iv:a0YBdW8j+2blI9SvWy9uUvv2M9uKO2I0X0PueB/iEDM=,tag:gH2Hr2rE+eI9BZOSkuPofw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
