k3s_token: ENC[AES256_GCM,data:OUFqp1BT2TUgwAOZOtx6YNMEOjPD5nLEJIxrneKlVY9jiq5ajP2cKBWTzbgesC4M0Ry+pTYEquHb+ctVSpzeBw==,iv:vVPhz7yqan7D1U49IsG104X6F9B4c0RWJ+AU3YP8gDo=,tag:r4c33yYYcR/VDFMS+FtLDQ==,type:str]
cert_manager_cloudflare_api_token: ENC[AES256_GCM,data:qHuFBF30UVNU62B2ncUiLncbm/MS/TyaT5wvfYFxTs1bQa2JDfkSAo/zQuyidolMj1jfZvU=,iv:wbe94i1dKWp7T5Vm9sgHYskIDlxHP/K2zapLGGKMiu8=,tag:yLF27SYzw8wlDjxdFondeQ==,type:str]
sops:
    age:
        - recipient: age1sl7k6nw404ykru7qyfnpvpamghrvjtd56j5kphk54tnhwawszf5sx4qfna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bjMrQVVBVS9lNzRQdllI
            SDQwYU1HdjR0VlFLN2pPOE5WZElLeUp5eGlvCkI5VHo2bTFOb0FQQ3JUSzRXVHpU
            dlVBRjJEcHgxNlJxUEE5QU5lMUgwRncKLS0tICt1dnpPb0FtWDdWU0hJZFNiUFBD
            dGhROVFkOHh3R0lmVXpvVmJkZGE1bE0Ksl2k9OgfFpP3RI+Re+yXN1gbXDyv3TP9
            QLMs1ny3GsGaJ/dfsYuG9BnE+5BKlOXt1GhJA+AknVslOwgqlWHDDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T18:57:34Z"
    mac: ENC[AES256_GCM,data:2ZaHFmvFTunE37MbSv35i6MJZO7UEj2zLe1m84uyqgt9v/imaP9Shhc3Cj3Um/8HzrIrGjvmMzUnIY2z3wGRPrL7ztUddZEjdJbGhvbjBkAMKTIpIhNVCmkneDfptMDzTiptU2MGcN+tVvt2b0WO8yYZ4+7x7CQzX3KUvTh71r0=,iv:MlbroGTaDLvQvH8HCiIZNvSfPAL2zuvcbwlCntbc4vs=,tag:rgxJnCClY/oF6GUUH8DuUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
